// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9K1QZ2jec0a5oRlWhQa7nAaVaSR_P3aE',
    appId: '1:342495160607:web:42e9cd00112eed4e84a82a',
    messagingSenderId: '342495160607',
    projectId: 'todo-dcacd',
    authDomain: 'todo-dcacd.firebaseapp.com',
    storageBucket: 'todo-dcacd.appspot.com',
    measurementId: 'G-BYT2R2B2TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuLJxm9ZWJYb_GPnXwiUVj895FLfjhImQ',
    appId: '1:342495160607:android:8775e8c2d6526ff084a82a',
    messagingSenderId: '342495160607',
    projectId: 'todo-dcacd',
    storageBucket: 'todo-dcacd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eQE5pZAkliXKX7dUDMGPMJUrwj1OCDI',
    appId: '1:342495160607:ios:7463783dc3b3617384a82a',
    messagingSenderId: '342495160607',
    projectId: 'todo-dcacd',
    storageBucket: 'todo-dcacd.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7eQE5pZAkliXKX7dUDMGPMJUrwj1OCDI',
    appId: '1:342495160607:ios:7463783dc3b3617384a82a',
    messagingSenderId: '342495160607',
    projectId: 'todo-dcacd',
    storageBucket: 'todo-dcacd.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9K1QZ2jec0a5oRlWhQa7nAaVaSR_P3aE',
    appId: '1:342495160607:web:d8656e5be543763584a82a',
    messagingSenderId: '342495160607',
    projectId: 'todo-dcacd',
    authDomain: 'todo-dcacd.firebaseapp.com',
    storageBucket: 'todo-dcacd.appspot.com',
    measurementId: 'G-RYEJLMGK0M',
  );

}